version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=VIP
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: VIP
    ports:
      - "3306:3306"
    volumes:
      - sql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  sql_data:
